### PR TITLE
Migrated protein folding algorithm and utils from Qiskit Nature.

### PR DESCRIPTION
**Pull request by dlasecki**
Original code:

https://github.com/Qiskit/qiskit-nature/tree/main/qiskit_nature/problems/sampling/protein_folding
https://github.com/Qiskit/qiskit-nature/tree/main/qiskit_nature/results/utils
https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/results/protein_folding_result.py
https://github.com/Qiskit/qiskit-nature/tree/main/test/problems/sampling/protein_folding
https://github.com/Qiskit/qiskit-nature/tree/main/test/results/utils
https://github.com/Qiskit/qiskit-nature/blob/main/test/results/test_protein_folding_result.py

### CODE REVIEW

**Comment by kevinsung** [comment]
Please add one or more tutorial notebooks for this module in the `docs/` directory.

**Comment by dlasecki** [comment]
> Please add one or more tutorial notebooks for this module in the `docs/` directory.

Good point, thanks. I forgot that we have a tutorial for this feature.

**Comment by kevinsung** [comment]
seems like an image is missing from the noteboov
image

**Comment by kevinsung** [comment]
Please execute the notebook and include the output cells. Also, there seems to be an extra blank cell at the end. I think after these are addressed, this will be good to go.

**Comment by dlasecki** [comment]
> Please execute the notebook and include the output cells. Also, there seems to be an extra blank cell at the end. I think after these are addressed, this will be good to go.

Thanks, done!

**Review by kevinsung — APPROVED** [review]

**Pull request merged**
